{% set name = "biopandas" %}
{% set version = "0.5.1" %}
{% set sha256 = "218021e1ed8b24150515a40ee2d4a7e4b4723b113f15d1369d5bbe1a8d966f04" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.16.2
    - pandas >=0.24.2
    - looseversion >=1.1.2  # uses hard pin upstream, relaxed to allow easier installation in conda envs
    - mmtf-python >=1.1.3  # uses hard pin upstream, relaxed to allow easier installation in conda envs
test:
  imports:
    - biopandas
    - biopandas.pdb
    - biopandas.testutils

about:
  home: http://github.com/BioPandas/biopandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Molecular Structures in Pandas DataFrames

  description: |
    BioPandas is a library for working with Protein Databank Files(PDB) written
    in Python 2.7 and Python 3.6.
  doc_url: http://biopandas.github.io/biopandas/
  dev_url: https://github.com/BioPandas/biopandas

extra:
  recipe-maintainers:
    - rasbt
    - souravsingh
    - moorepants
