{% set name = "biopandas" %}
{% set version = "0.2.2" %}
{% set sha256 = "7e7f0651f86d44ac7ea0364b6d1ca650871bc767ca3d2cd4d9f84ea78428e033" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - numpy
    - pandas

test:
  imports:
    - biopandas
    - biopandas.pdb
    - biopandas.testutils

about:
  home: http://github.com/rasbt/biopandas
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'Molecular Structures in Pandas DataFrames'

  description: |
    BioPandas is a library for working with Protein Databank Files(PDB)
    written in Python 2.7 and Python 3.5. 
  doc_url: http://rasbt.github.io/biopandas/
  dev_url: https://github.com/rasbt/biopandas

extra:
  recipe-maintainers:
    - rasbt
    - souravsingh
