{% set name = "biopandas" %}
{% set version = "0.2.5" %}
{% set sha256 = "0c3f770dabf27a4b405ed7606ce90f62e47f3d85d7385b13b8a7ae9964ac8bec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    
  run:
    - python
    - numpy
    - pandas

test:
  imports:
    - biopandas
    - biopandas.pdb
    - biopandas.testutils

about:
  home: http://github.com/rasbt/biopandas
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'Molecular Structures in Pandas DataFrames'

  description: |
    BioPandas is a library for working with Protein Databank Files(PDB)
    written in Python 2.7 and Python 3.6. 
  doc_url: http://rasbt.github.io/biopandas/
  dev_url: https://github.com/rasbt/biopandas

extra:
  recipe-maintainers:
    - rasbt
    - souravsingh
