{% set name = "biopandas" %}
{% set version = "0.2.9" %}
{% set sha256 = "417e84bac4dddf6728a4c1960efef35f7bdb72da5688317e23c0bcd964645f83" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy >=1.16.2
    - pandas >=0.24.2

test:
  imports:
    - biopandas
    - biopandas.pdb
    - biopandas.testutils

about:
  home: http://github.com/BioPandas/biopandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Molecular Structures in Pandas DataFrames

  description: |
    BioPandas is a library for working with Protein Databank Files(PDB) written
    in Python 2.7 and Python 3.6.
  doc_url: http://biopandas.github.io/biopandas/
  dev_url: https://github.com/BioPandas/biopandas

extra:
  recipe-maintainers:
    - rasbt
    - souravsingh
    - moorepants
