travis:
  secure:
    BINSTAR_TOKEN: c8l5QOD4rWZyAO7dRzceMOFfjcat36cofQ6wub8c0R3sYoZ1bZjG95mLlEy4QkdrujO9IFZmHtUEv4daSpD0oei9MFW4OtswfQ8OOk6W7HlRFifgdEN0uWuQOnRqSV5UKYvdjcIlkR/xZ0BM4/uWHVz40kLJTRUsxMn5RHYWIhkSpvEjSXP7sgVXN5uCPNn1tMrY4PjCBjMq9sHY05lVeVdO46vuHTKXGvCgMI0cXvnr+dBaX08fWlxYfpFSvQe4XAZjFrt0BEkgcq25BXOUYDiiZegWHKVeFIGSTCjWN/mfQB3e03Bu6JjTf7Ik9FdbpsFFh6/EA8GrnKTTTqfUXT1qBelaZO0wNPgY/QvqngVXe898+O6Vk+GjDuhg7nRel6e6NIL297r6VMLDPdY4vIXnBPsVYLYYKDOVg3VYVBvpot/L6IaGZYPofI91/+ul04u8VxYgkEitqq+CP2swUYzjukeF2WITAM0h2AONlo0pNbxuEh+2qDEz26jh07MShLxshiXy8ZJFUOvJuMWFjnq4tFs4DE2vZHhRrhVCtaezwnIME4SP3pqH2k+fkRYbpeFO4wc/K/Finjv18EuG5siKuHz9l5dgJLY3To3kQvni8vin1HX33uVfoDY60TjMK6Kzl6EpXZ/e7E/yFFGQu/Q/0DJ+qKCla3KvRmUCQFI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
