travis:
  secure:
    BINSTAR_TOKEN: boLauogX6F+OjWUJs0tPDBk1L/08Ew79QDA4BGDNmWw++s59GvNvjZgJXjUC7HQLUQnXHaOKkAVvh/4yKtJYi7SlFNQwR5F1QjXn2F0ZAqDyB2opsfAhrab8DsXEzozOoMH64NKoy5AVDh6k+bXmQOEp8DN9U/b1bBp9mrQshnDxxmmJsq9P7o2T/O+hlnmlKBGmLaYIj7hYXy4fKYAJvxrOLsufiHAYrcgYDskgzfC2azOGmmsrI1X7vuYk0j5KqwFWjZ8hU1+XCHbjVoEd8NXwYBTA3nnyyyHIAgPbW8+kvrh0KpQkMj29Y75+wXLmISezDQsXhHtmdSxcM5HEiCk+DD7xq0LKybnAYegvNIJFdUGZxL6oj4RK89hwU1ESn7+ZxWXoEj+s6ccS15SfYZprIG0tRllNY4S190jplbEnmPFkQPhwCujTvVjtD6tpA1XT+QcQX7n/epdCC56WH2FikG5I0M3rvVYdaawWK0UGtMV1TeA4mcJY4kW+5pZvghn4WXwiXblHdxeFqgek20ARqeZJh7iFSKh8clftuEsxPbN6ispq/jajwvAoGR7iPRn5C9O5CKDOTQN/icWrtgJe6bHuBIJAGo0b3t5dw6HnoVTtXNywgxtarPRHzxSgebA+R5/taZ8xW5FRlD0alpV4I/jS3csrSft3MdpGIT4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
